blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/mjangir/use-react-slider/discussions
    about: Ask questions and discuss with other community members
  - name: Join Discord
    url: https://discord.gg/92GTdY89
    about: Chat with other community members in real-time
