import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { SliderProvider, CurrentSlide, useReactSlider } from 'use-react-slider';

const MyCustomComponent = () => (
  <div style={{ color: 'white' }}>
    <h1>This is my first component</h1>
  </div>
);

const slides: any = [
  {
    url: 'https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ',
    component: MyCustomComponent,
  },
  'https://i.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68',
  'https://i.picsum.photos/id/1000/5626/3635.jpg?hmac=qWh065Fr_M8Oa3sNsdDL8ngWXv2Jb-EE49ZIn6c0P-g',
  'https://i.picsum.photos/id/1004/5616/3744.jpg?hmac=Or7EJnz-ky5bsKa9_frdDcDCR9VhCP8kMnbZV6-WOrY',
  'https://i.picsum.photos/id/101/2621/1747.jpg?hmac=cu15YGotS0gIYdBbR1he5NtBLZAAY6aIY5AbORRAngs',
];

function MainSlider() {
  const { navigateLeft, navigateRight, navigateToIndex, slides } =
    useReactSlider();
  return (
    <>
      <CurrentSlide>
        {(slide: any) => {
          const Renderable = slide.component;

          return Renderable ? <Renderable /> : null;
        }}
      </CurrentSlide>
      <button
        onClick={navigateRight}
        style={{ position: 'absolute', right: 0 }}
      >
        Next
      </button>
      <button onClick={navigateLeft} style={{ position: 'absolute' }}>
        Prev
      </button>
      <button
        onClick={() => navigateToIndex(slides.length - 1)}
        style={{ position: 'absolute', top: '100px' }}
      >
        Jump to last slide
      </button>
    </>
  );
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ width: '1000px', height: '600px' }}>
          <SliderProvider slides={slides}>
            <MainSlider />
          </SliderProvider>
        </div>
      </main>
    </div>
  );
};

export default Home;
